<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Platforms>x64</Platforms>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>TRACE;DOTNET_STARNDARD</DefineConstants>
    <OutputPath>../../release/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AssemblyName>efkc</AssemblyName> <!-- [UAA] -->
    <RootNamespace>EffekseerValidate</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EffekseerCore\EffekseerCore.csproj" />
  </ItemGroup>

</Project>
